services:
  database:
    image: postgres:18-alpine3.22
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: postgres -c shared_preload_libraries=pg_stat_statements

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: 
      - -path=/migrations/
      - -database=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@database:5432/${POSTGRES_DB:-postgres}?sslmode=disable
      - up
    depends_on:
      database:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      target: run
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      PROVIDERS_CONFIG_PATH: "/providers.yml"
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY:-}"
      JWT_SECRET: "${JWT_SECRET:-secret}"
      BACKEND_PORT: "${BACKEND_PORT:-8080}"
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@database:5432/${POSTGRES_DB:-postgres}?sslmode=disable"
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./client
    depends_on:
      - backend
    ports:
      - "${CLIENT_PORT:-3000}:80"
    environment:
      VITE_API_BASE_URL: "/api"

volumes:
  postgres_data: